### PR TITLE
Updated WP and PHP support details

### PR DESCRIPTION
**Pull request by ericjsilva**

### CODE REVIEW

**Comment by ericjsilva** [comment]
@justdave not sure how I missed checking in the readme, but here it is. Thanks.

**Comment by justdave** [comment]
Huh.  I was thinking there was supposed to be a specific format for that because Wordpress read from it populating the plugins page on the site, but I guess that only applies to the plugin file itself, which is actually missing this information and should have it there as well.

See https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

**Comment by justdave** [comment]
Oh, the format of the README does matter, but only if we're getting it listed in the WordPress Plugin Directory (which we don't).
https://wordpress.org/plugins/developers/#readme

**Comment by ericjsilva** [comment]
@justdave PHP 5.6 is EOL. People should not be using it. Everyone should be on 7.2 or 7.3 by now. I don't see any significant risk dropping legacy support.

**Pull request merged**
