### PR TITLE
OALM 4.2.0 compatibility

### PR DESCRIPTION
**Pull request by ericjsilva**
Added changes needed to support the new BSA registration fields in OALM 4.2.0 and later.

### CODE REVIEW

**Comment by justdave** [comment]
I assume we're removing the vendor directory because I should be running composer to pull it in as part of the build process when I generate the plugin instead of having it in the code repo. :-)

**Comment by ericjsilva** [comment]
> I assume we're removing the vendor directory because I should be running composer to pull it in as part of the build process when I generate the plugin instead of having it in the code repo. :-)

Yes.

**Comment by ericjsilva** [comment]
> "BSA ID Not Found" is not "Not Registered". It should be treated the same as "BSA ID Found - Data Mismatch". I think the previous concept of "Not Registered" in the new system only occurs when the status is "BSA ID Verified" and "BSA Reg." is 0. For someone to be considered registered you need both bsa_verify_status == "BSA ID Verified" and bsa_reg == 1.

Dave, when I looked at these records in OALM, they are showing as Not Registered.

**Comment by ericjsilva** [comment]
screen shot 2019-02-17 at 6 01 39 pm

**Comment by justdave** [comment]
screen shot 2019-02-17 at 6 10 24 pm

**Comment by justdave** [comment]
It shows "Not Active" in the Registration Status field no matter what the status is if the status is anything other than "BSA ID Verified".  i.e. if the status is not "BSA ID Verified" then you can completely ignore the Reg Status field.  If the status *is* "BSA ID Verified" then you have to further check the Reg Status field to see whether their registration is active or not.

**Comment by ericjsilva** [comment]
@justdave does this logic match what you are thinking?

```php
$bsa_verify_status = $results->bsa_verify_status;
                if ($bsa_verify_status == "") {
                    $bsa_verify_status = "Never Run";
                }

                $bsa_reg = $results->bsa_reg ? "Registered" : "Not Registered";
                if ($bsa_verify_status !== "BSA ID Verified") {
                    $bsa_reg = "Not Registered";
                }

                $bsa_reg_overridden = $results->bsa_reg_overridden;
                if ($bsa_reg_overridden) {
                    $bsa_reg = $bsa_reg . " (overridden)";
                }
```

**Comment by justdave** [comment]
I guess a better way to look at it would be: if BSA Reg says they're registered then they are. If it says they're not, then we need to look at the Status field to see why.  This is all pseudocode, not necessarily following the variables in the real code:

``` php
if ($bsa_reg == "Registered") {
     // Member is a registered BSA Member in good standing
} else {
    if ($bsa_verify_status == "BSA ID Verified") {
        // registration exists but has expired
    } else if ($bsa_verify_status == "BSA ID Not Found") {
        // Couldn't find a record with that BSA ID in the BSA's database
    } else if ($bsa_verify_status == "BSA ID Found - Data Mismatch") {
        // We found the ID, but the other data we have on you doesn't match
    }
}
```

**Comment by ericjsilva** [comment]
@justdave Are you focused on the the message that is returned to the user in the following code: https://github.com/oabsa/dues-lookup/blob/oalm-4.2.0-compatibility/includes/user-facing-lookup-page.php#L91-L145

Are you just looking to ensure we are sending the most accurate message back?

**Comment by justdave** [comment]
Yeah, that's pretty much where I started from and why I went through so many iterations trying to explain it. :-)  The section where it was displaying info back to the user didn't look like it was saying the right thing.

**Comment by ericjsilva** [comment]
OK. I was focused on a different area of the code. Let me make some changes and I will update the PR.

**Comment by ericjsilva** [comment]
@justdave I've updated the messages. Let me know if you are satisfied.

**Comment by justdave** [comment]
I like it.

Now for real-world testing....

`composer install` throws the following warnings:
>Deprecation warning: Your package name dues-lookup is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

>Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

`composer update` then throws the following error:
>Reading composer.json of https://github.com/oabsa/dues-lookup (master)
>Skipped branch master, Unknown package has no name defined ({"require":{"phpoffice\/phpspreadsheet":"^1.2"},"time":"2018-08-02T12:26:06+00:00","version":"dev-master","version_normalized":"9999999-dev","name":null,"dist":null,"source":{"type":"git","url":"https:\/\/github.com\/oabsa\/dues-lookup","reference":"8914b0bcb6ff1007441fe822ca6429845f55a201"}}).


When I look up the ID of a member who has their dues paid, whether or not they have an active registration, I get the plugin output without the website template, just a blank white page with the results table at the top.  Looking up someone who is not paid gets the normal page.

**Comment by justdave** [comment]
I assume the vendor name thing should be oabsa/dues-lookup to match the master repo.

**Comment by justdave** [comment]
Your typo fix commit fixed the almost-blank page problem.  I hadn't pulled that commit yet when I was testing.

**Comment by ericjsilva** [comment]
@justdave fixed the composer issue.

I am not having any rendering issues on https://kittatinny5.org/dueslookup/

**Comment by justdave** [comment]
> I am not having any rendering issues on https://kittatinny5.org/dueslookup/

Yeah, your "typo fix" commit fixed that.  I hadn't pulled that commit yet when I was initially testing.

**Comment by justdave** [comment]
Looks good to me, I'll merge. :-)

**Comment by justdave** [comment]
Thanks a bunch!

**Pull request merged**
